-- =============================================================================
-- PulsePPG Stress Monitor — Esquema de PostgreSQL (Fase 1)
--
-- Lo ejecuta automáticamente la imagen oficial de postgres la primera vez que
-- arranca con el volumen vacío (/docker-entrypoint-initdb.d/). Es re-ejecutable
-- a mano sin romper nada: todo usa IF NOT EXISTS / OR REPLACE.
--
-- Convención de nombres:
--   sessions.id          -> clave interna (entero). Es el <session_pk> que el
--                           watcher pasa a Spark y al modelo.
--   sessions.session_id  -> identificador externo generado por la Pi
--                           (<timestamp>_<device_id>). Es la clave de idempotencia.
--   <tabla>.session_pk   -> FK hacia sessions.id en las tablas hijas. Se llama
--                           session_pk (no session_id) para no confundirla con el
--                           identificador externo de texto.
--
-- Unidades: t, t_start, t_end en segundos desde el inicio de la captura (mismo
-- eje que el campo "t" del JSONL). rr_interval, sdnn y rmssd en milisegundos.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. sessions — una fila por captura de 5 minutos.
--    Resuelve: identidad de la sesión, idempotencia del POST (session_id único),
--    máquina de estados (status) y trazabilidad hacia el archivo crudo
--    (checksum SHA-256 del JSONL que la Pi conserva como respaldo).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    TEXT        NOT NULL,
    device_id     TEXT,
    start_time    TIMESTAMPTZ NOT NULL,
    duration_sec  REAL,                       -- parcial si la sesión se abortó
    quality       TEXT,
    checksum      TEXT,                       -- SHA-256 recibido en POST /upload
    status        TEXT        NOT NULL DEFAULT 'created',
    status_detail TEXT,                       -- motivo del último cambio (ej. "abort", traza de error)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Idempotencia: un reintento del POST con el mismo session_id no crea otra fila.
    CONSTRAINT uq_sessions_session_id UNIQUE (session_id),
    -- Solo los cinco estados de la máquina de estados (sección 7 de la propuesta).
    CONSTRAINT ck_sessions_status
        CHECK (status IN ('created', 'uploaded', 'processing', 'ready', 'error')),
    CONSTRAINT ck_sessions_session_id_not_empty CHECK (session_id <> ''),
    CONSTRAINT ck_sessions_duration CHECK (duration_sec IS NULL OR duration_sec >= 0),
    CONSTRAINT ck_sessions_checksum
        CHECK (checksum IS NULL OR checksum ~ '^[0-9a-f]{64}$')
);

-- Limpieza de retención (ORDER BY start_time DESC LIMIT 10) y GET /api/sesiones.
CREATE INDEX IF NOT EXISTS idx_sessions_start  ON sessions (start_time DESC);
-- Recuperación al arrancar: el watcher busca sesiones en 'uploaded' o 'processing'.
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions (status);
-- La búsqueda por session_id (GET /api/estado/<session_id>, idempotencia del POST)
-- ya la cubre el índice que crea uq_sessions_session_id.

-- -----------------------------------------------------------------------------
-- 2. metrics — métricas HRV globales de la sesión (las escribe Spark).
--    Resuelve: relación 1:1 con la sesión. La PK sobre session_pk impide que un
--    reintento de Spark deje dos filas: debe usar INSERT ... ON CONFLICT.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS metrics (
    session_pk  INTEGER PRIMARY KEY
                REFERENCES sessions (id) ON DELETE CASCADE,
    bpm         REAL,
    sdnn        REAL,                         -- ms
    rmssd       REAL,                         -- ms
    pnn50       REAL,                         -- %
    computed_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_metrics_bpm   CHECK (bpm   IS NULL OR bpm > 0),
    CONSTRAINT ck_metrics_sdnn  CHECK (sdnn  IS NULL OR sdnn >= 0),
    CONSTRAINT ck_metrics_rmssd CHECK (rmssd IS NULL OR rmssd >= 0),
    CONSTRAINT ck_metrics_pnn50 CHECK (pnn50 IS NULL OR pnn50 BETWEEN 0 AND 100)
);

-- -----------------------------------------------------------------------------
-- 3. peaks — cada latido detectado por Spark.
--    Resuelve: trazabilidad de las métricas hasta la señal. Con "t" se localiza
--    la muestra exacta del JSONL; los rr_interval son la entrada de SDNN/RMSSD.
--    UNIQUE (session_pk, t) evita duplicar picos si Spark se reintenta, y su
--    índice sirve también para "picos de la sesión X ordenados por t", así que
--    no hace falta un índice aparte sobre session_pk.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS peaks (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_pk  INTEGER NOT NULL
                REFERENCES sessions (id) ON DELETE CASCADE,
    t           REAL    NOT NULL,             -- s, eje del JSONL
    rr_interval REAL,                         -- ms; NULL en el primer pico

    CONSTRAINT uq_peaks_session_t UNIQUE (session_pk, t),
    CONSTRAINT ck_peaks_t  CHECK (t >= 0),
    CONSTRAINT ck_peaks_rr CHECK (rr_interval IS NULL OR rr_interval > 0)
);

-- -----------------------------------------------------------------------------
-- 4. stress_windows — clasificación del modelo por ventana de 30 s.
--    Resuelve: línea de tiempo de estrés de los resultados. UNIQUE
--    (session_pk, t_start) hace idempotente el reintento del modelo y su índice
--    cubre "ventanas de la sesión X ordenadas por tiempo".
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stress_windows (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_pk  INTEGER NOT NULL
                REFERENCES sessions (id) ON DELETE CASCADE,
    t_start     REAL    NOT NULL,             -- s
    t_end       REAL    NOT NULL,             -- s
    level       TEXT    NOT NULL,             -- etiqueta que devuelva Pulse-PPG
    score       REAL,

    CONSTRAINT uq_windows_session_start UNIQUE (session_pk, t_start),
    CONSTRAINT ck_windows_range CHECK (t_start >= 0 AND t_end > t_start)
);

-- -----------------------------------------------------------------------------
-- 5. session_events — historial de transiciones de estado.
--    Resuelve: "cada resultado se rastrea hasta su origen" y "ninguna sesión
--    queda en limbo". sessions.status solo guarda el estado actual; esta tabla
--    guarda cuándo y por qué pasó por cada uno (incluido el motivo de un
--    'error'). La llena un trigger, así que ningún componente puede olvidarse
--    de registrar una transición.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS session_events (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_pk  INTEGER NOT NULL
                REFERENCES sessions (id) ON DELETE CASCADE,
    from_status TEXT,                         -- NULL en la creación de la sesión
    to_status   TEXT    NOT NULL,
    detail      TEXT,                         -- copia de sessions.status_detail
    changed_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

-- Historial de una sesión en orden cronológico (vista de "detalle técnico").
CREATE INDEX IF NOT EXISTS idx_events_session
    ON session_events (session_pk, changed_at);

-- -----------------------------------------------------------------------------
-- 6. Máquina de estados aplicada en la base.
--    Resuelve: que una transición inválida (ej. ready -> processing) falle con
--    error en lugar de pasar en silencio, venga del componente que venga.
--
--      created -> uploaded -> processing -> ready
--         |                      |
--         +-> error              +-> error
--
--    Reglas:
--      · INSERT solo en 'created' (servidor-web al recibir start) o en
--        'uploaded' (POST de una sesión que nunca se registró; pregunta 3).
--      · Repetir el estado actual es un no-op permitido: así el watcher puede
--        reintentar "SET status = 'uploaded'" sin romper la idempotencia.
--      · Cualquier UPDATE refresca updated_at.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION sessions_enforce_state() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status NOT IN ('created', 'uploaded') THEN
            RAISE EXCEPTION 'sesión %: estado inicial inválido "%" (solo created o uploaded)',
                NEW.session_id, NEW.status
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;

    NEW.updated_at := now();

    IF NEW.status IS DISTINCT FROM OLD.status
       AND (OLD.status, NEW.status) NOT IN (
            ('created',    'uploaded'),
            ('created',    'error'),
            ('uploaded',   'processing'),
            ('processing', 'ready'),
            ('processing', 'error'))
    THEN
        RAISE EXCEPTION 'sesión %: transición inválida % -> %',
            OLD.session_id, OLD.status, NEW.status
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_sessions_enforce_state
    BEFORE INSERT OR UPDATE ON sessions
    FOR EACH ROW EXECUTE FUNCTION sessions_enforce_state();

-- Registra en session_events la creación y cada cambio real de estado.
CREATE OR REPLACE FUNCTION sessions_log_event() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO session_events (session_pk, from_status, to_status, detail)
        VALUES (NEW.id, NULL, NEW.status, NEW.status_detail);
    ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO session_events (session_pk, from_status, to_status, detail)
        VALUES (NEW.id, OLD.status, NEW.status, NEW.status_detail);
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE TRIGGER trg_sessions_log_event
    AFTER INSERT OR UPDATE OF status ON sessions
    FOR EACH ROW EXECUTE FUNCTION sessions_log_event();

COMMIT;
